name: 'proof-of-work-submitter'
description: 'Submits a proof of work to the contract'
author: 'kudos.ink'

# Define your inputs here.
inputs:
  ws-provider-url:
    description: 'node url'
    required: true
  mnemonic-phrase:
    description: 'seed phrase'
    required: true
  contract-address:
    description: 'address of the contract'
    required: true
  contract-abi:
    description: 'abi of the contract'
    required: true
  contribution-id:
    description: 'id of the contribution'
    required: true
  contributor-identity:
    description: 'identity of the contributor'
    required: true

# Define your outputs here.
outputs:
  hash:
    description: 'Transaction hash'

runs:
  using: node20
  main: dist/index.js
